version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6380
    command: npm run start:dev
    depends_on:
      - redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6380"
    command: ["redis-server", "--port", "6380"]
